<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>CenterICQ</textheader> 
  <namedlink href="%%documentsurl%%images/centericq.gif">
    <rimg href="%%documentsurl%%images/centericq.jpg" />
  </namedlink>
  <text>Centericq is a text mode menu- and window-driven IM interface that supports the ICQ2000, Yahoo!, AIM, IRC, MSN, Gadu-Gadu and Jabber protocols. Actually, it was written since I didn't find any usable software of this kind that would suit me perfectly. Brief list of program's features follows: Text mode user interface, General instant messaging features, ICQ support, Yahoo! support, Jabber support, IRC support, Integrated client for LiveJournal and more ...</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://konst.org.ua/en/centericq/</link>
  </text>
</content>

