<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>finch</textheader> 
  <namedlink href="%%documentsurl%%images/finch.png">
    <rimg href="%%documentsurl%%images/finch.jpg" />
  </namedlink>
  <text>finch is a console-based modular messaging client based on libpurple which is capable of connecting to AIM, MSN, Yahoo!, XMPP, ICQ, IRC, SILC, Novell GroupWise, Lotus Sametime, Zephyr, Gadu-Gadu, and QQ all at once. It has many common features found in other clients, as well as many unique features. Finch is not endorsed by or affiliated with America Online, ICQ, Microsoft, or Yahoo.</text>  
  <text>
    <noop>Homepage: </noop>
    <link>http://pidgin.im</link>
  </text>
</content>
