<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Licq (console plugin) - Linux ICQ</textheader> 
  <namedlink href="%%documentsurl%%images/licq.gif">
    <rimg href="%%documentsurl%%images/licq.jpg" />
  </namedlink>
  <text>Licq is the best ICQ client for Linux which I know from. Commonly, Licq is used with an Qt or GTK Graphical User Interface but in the standard Licq destribution there also exists an plugin which enables you to use this client through the console-shell.  Licq is developed without any help from Mirabilis.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.licq.org</link>
  </text>
</content>
