<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>mICQ (Climm) - Matt's ICQ Clone</textheader> 
  <namedlink href="%%documentsurl%%images/micq.gif">
    <rimg href="%%documentsurl%%images/micq.jpg" />
  </namedlink>
  <text>As you may see in the name, mICQ is yet another ICQ clone. mICQ completely is based on a ASCII-interface and includes many of the important ICQ features. mICQ is developed without any help from Mirabilis. mICQs new name is now CLIMM</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.climm.org</link>
  </text>
</content>
