<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>silc - client for SILC, a secure and flexible conferencing network</textheader> 
  <namedlink href="%%documentsurl%%images/irssi.png">
    <rimg href="%%documentsurl%%images/irssi.jpg" />
  </namedlink>
  <text>SILC (Secure Internet Live Conferencing) is a secure conferencing network.   Silc is the SILC client which is used to connect to SILC server and the SILC network. The silc client resembles IRC clients (like IRSSI) to make the using easier for new users.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.silcnet.org/software/users/client/</link>
  </text>
</content>
