<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Ysm - (Y)OU (S)ICK (M)E</textheader> 
  <namedlink href="%%documentsurl%%images/ysm.png">
    <rimg href="%%documentsurl%%images/ysm_s.png" />
  </namedlink>
  <text>You Sick ME is a portable open source console ICQ client written in the C language, under the GPL license. YSM is one of the new generation clients due to the sudden modifications the ICQ protocol suffered after Mirabilis joined the dark-side of the force (AOL). This is the reason why most ICQ clients ended up with mal-functions or unable to use the IM network at all.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://ysmv7.sourceforge.net/</link>
  </text>
</content>
