<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/kinder_der_ewigkeit.jpg">
		<rimg href="%%documentsurl%%images/kinder_der_ewigkeit-small.jpg" />
	</namedlink>
	<textheader>Kinder der Ewigkeit</textheader>
	<text>Ex-Killer Esebian wollte seine Ruhe und hatte sich vom Leben eines Killers an das eines Wissenschaftlers gew&ouml;hnt - damit ist sein Weg zur "teuren" Unsterblichkeit zwar schwerer und steiler, aber daf&uuml;r auch sicherer und ruhiger. Bis er von m&auml;chtigen Wesen gezwungen wird, eine der einflussreichsten Pers&ouml;nlichkeiten der Galaxis zu t&ouml;ten.</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Space Opera, Fantasy, Thriller</text>
		</enumitem>
		<enumitem>
			<text>Autor: Andreas Brandhorst</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 688</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: 5/5</text>
		</enumitem>
	</enumeration>
</content>
