<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/diamant.jpg">
		<rimg href="%%documentsurl%%images/diamant-small.jpg" />
	</namedlink>
	<textheader>Diamant</textheader>
	<text>Ein gigantisches Sternenreich, das sich in inneren Konflikten aufreibt und zu verfallen droht. Eine au&szlig;erirdische Zivilisation, die einen geheimnisvollen Plan verfolgt. Und eine junge Raumschiffpilotin, die auf einem abgelegenen Planeten das gr&ouml;&szlig;te R&auml;tsel der Menschheitsgeschichte zu l&ouml;sen versucht.</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Space Opera, Fantasy, Zeitreise</text>
		</enumitem>
		<enumitem>
			<text>Autor: Andreas Brandhorst</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 589</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: 5/5</text>
		</enumitem>
	</enumeration>
</content>
