<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/das_restaurant_am_ende_des_universums.jpg">
		<rimg href="%%documentsurl%%images/das_restaurant_am_ende_des_universums-small.jpg" />
	</namedlink>
	<textheader>Das Restaurant am Ende des Universums</textheader>
	<text> Arthur Dent hat sich auf seiner OdysSee wirklich eine Pause verdient - und wo sonst k&ouml;nnte man die einlegen, als im Milliways, dem Restaurant am Ende des Universums?</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Humor, Fantasy</text>
		</enumitem>
		<enumitem>
			<text>Autor: Douglas Adams</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 240</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: 4/5</text>
		</enumitem>
	</enumeration>
</content>
