<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/per_anhalter_durch_die_galaxis.jpg">
		<rimg href="%%documentsurl%%images/per_anhalter_durch_die_galaxis-small.jpg" />
	</namedlink>
	<textheader>Per Anhalter durch die Galaxis</textheader>
	<text>W&auml;hrend der Gro&szlig;teil der Menschheit von dem Eintreffen einer au&szlig;erirdischen Bautruppe ziemlich &uuml;berrascht wird - und f&uuml;r einen kurzen Moment die &Uuml;berraschung in Panik umschl&auml;gt als klar wird, da die Erde einer geplanten Hyperraum-Autobahn im Wege steht und daher vernichtet werden mu&szlig; - gelingt es zumindest dem seit 15 Jahren auf der Erde gestrandeten Au&szlig;erirdischen Ford Prefect und seinem durch und durch irdischen Freund Arthur Dent - der bis vor kurzem noch gen&uuml;gend andere Probleme hatte - mit ihrem Multifunktionshandtuch auf sich aufmerksam zu machen und als Anhalter mitgenommen zu werden.</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Humor, Fantasy</text>
		</enumitem>
		<enumitem>
			<text>Autor: Douglas Adams</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 208</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: 4/5</text>
		</enumitem>
	</enumeration>
</content>
