<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/das_leben_das_universum_und_der_ganze_rest.jpg">
		<rimg href="%%documentsurl%%images/das_leben_das_universum_und_der_ganze_rest-small.jpg" />
	</namedlink>
	<textheader>Das Leben, das Universum und der ganze Rest</textheader>
	<text>Endlich wieder auf der Erde! Nach seiner atemberaubenden Reise durch die Galaxis ist Arthur Dent wieder gut auf dem Heimatplaneten gelandet. Einziger Haken: Er ist zwei Millionen Jahre fr&uuml;her in einer Steinzeith&ouml;hle gestrandet. Zum Gl&uuml;ck ist Ford Prefekt an seiner Seite und der wei&szlig; auch schon, wie sie zu einem Ticket zu den Sternen kommen. Eine klitzekleine Bedingung gilt es daf&uuml;r zu erf&uuml;llen: Das Universum zu retten.</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Humor, Fantasy</text>
		</enumitem>
		<enumitem>
			<text>Autor: Douglas Adams</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 224</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: 3/5</text>
		</enumitem>
	</enumeration>
</content>
