<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/machts_gut_und_danke_fuer_den_fisch.jpg">
		<rimg href="%%documentsurl%%images/machts_gut_und_danke_fuer_den_fisch-small.jpg" />
	</namedlink>
	<textheader>Macht's gut, und danke f&uuml;r den Fisch</textheader>
	<text>Arthur Dents Flucht von dem absolut unbedeutenden, kleinen blaugr&uuml;nen Planeten in den unerforschten Ein&ouml;den des total aus der Mode gekommenen Ausl&auml;ufers des westlichen Spiralarms der Galaxis nimmt kein Ende. Im vierten Band der Hitchhiker-Trilogie kehrt der m&uuml;de Wanderer durch die Weiten des Weltenraumes auf die Erde zur&uuml;ck. Sie wurde wohl doch nicht gesprengt. Oder doch?</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Humor, Fantasy</text>
		</enumitem>
		<enumitem>
			<text>Autor: Douglas Adams</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 192</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: 2/5</text>
		</enumitem>
	</enumeration>
</content>
