<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Midnight Commander</textheader> 
  <namedlink href="%%documentsurl%%images/mc.gif">
    <rimg href="%%documentsurl%%images/mc.jpg" />
  </namedlink>
  <text>The midnight commander is a very powerfull text-based filemanager which also may be used as a FTP client. If you are familiar to tho Norton Commander then this program is a must!</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.midnight-commander.org</link>
  </text>
</content>
