<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Screen - Screen manager with VT100/ANSI terminal emulation</textheader>
  <namedlink href="%%documentsurl%%images/screen.gif">
    <rimg href="%%documentsurl%%images/screen.jpg" />
  </namedlink>
  <text>Screen is a full-screen window manager that multiplexes a physical  terminal  between  several  processes (typically interactive shells).  Each virtual terminal  provides  the functions  of  a DEC VT100 terminal and, in addition, sev­ eral control functions from the ISO 6429  (ECMA  48,  ANSI X3.64) and ISO 2022 standards (e.g. insert/delete line and support for multiple character sets).  There is a  scroll­ back  history buffer for each virtual terminal and a copy- and-paste  mechanism  that  allows  moving  text   regions between windows.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.gnu.org/software/screen</link>
  </text>
</content>
