<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/endymion.jpg">
		<rimg href="%%documentsurl%%images/endymion-small.jpg" />
	</namedlink>
	<textheader>Pforten der Zeit / Die Auferstehung</textheader>
	<text>Mit den Hyperion-Romanen l&auml;utete Dan Simmons eine neue &Auml;ra der Space Opera ein -- und setzte gleichzeitig einen bis heute unerreichten Standard. Mit den beiden jetzt im Sammelband erschienen Endymion-Romanen setzt er die Geschichte fort und bringt sie zu einem grandiosen Abschluss.</text>
	<text>Sie wird erz&auml;hlt von ihrem Helden, Raul Endymion, der -- zum Tode verurteilt -- auf sein Leben zur&uuml;ckblickt. Er sitzt in einer Schr&ouml;dinger-Katzenkiste, nach einem uralten R&auml;tsel der Quantenphysik weder tot noch lebendig. Und er erinnert sich an seine Reise als Besch&uuml;tzer des M&auml;dchens Aenea, der Tochter des John-Keats-Cybriden aus Hyperion. Aenea wird verfolgt von dem "Pax", einer Mutation der katholischen Kirche in weiter Zukunft, die die Menscheit beherrscht und ihr mithilfe eines Parasiten eine scheinbare Unsterblichkeit verschafft hat. Eine wilde Flucht beginnt, die mithilfe der Farcaster-Portale durch die verschiedensten Welten bis zur Alten Erde f&uuml;hrt. W&auml;hrend dieser Reise w&auml;chst Aenea zur Frau heran und entwickelt sich zu "Derjenigen die lehrt" -- eine t&ouml;dliche Bedrohung f&uuml;r das Pax.</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction</text>
		</enumitem>
		<enumitem>
			<text>Autor: Dan Simmons; &Uuml;bersetzer: Joachim K&ouml;rber</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 1326</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: ?/5</text>
		</enumitem>
	</enumeration>
</content>
