<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/nes-super-mario-bros1.jpg">
		<rimg href="%%documentsurl%%images/nes-super-mario-bros1-small.jpg" />
	</namedlink>
	<textheader>Super Mario Bros</textheader>
	<enumeration>
		<enumitem>
			<text>Platform: NES</text>
		</enumitem>
		<enumitem>
			<text>Publisher: Nintendo</text>
		</enumitem>
		<enumitem>
			<text>Release year: 1985</text>
		</enumitem>
		<enumitem>
			<text>Size: 0.375 Megs</text>
		</enumitem>
	</enumeration>
</content>
