<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Calcurse - text-based organizer</textheader>
  <namedlink href="%%documentsurl%%images/calcurse.png">
    <rimg href="%%documentsurl%%images/calcurse.jpg" />
  </namedlink>
  <text>Calcurse is a text-based calendar and scheduling application. It helps keeping track of events, appointments and everyday  tasks. A configurable  notification system reminds user of upcoming deadlines, and the curses based interface can be customized to suit user  needs. All of the commands are documented within an online help system.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://culot.org/calcurse/</link>
  </text>
</content>
