<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>rtorrent</textheader> 
  <namedlink href="%%documentsurl%%images/rtorrent.png">
    <rimg href="%%documentsurl%%images/rtorrent.jpg" />
  </namedlink>
  <text>rTorrent is a text-based ncurses BitTorrent client written in C++, based on the libtorrent libraries for UNIX (not to be confused with libtorrent (Rasterbar) by Arvid Norberg), "with a focus on high performance and good code". rTorrent packages are available for various Linux distributions and Unix-like systems, and it will compile and run on nearly every POSIX-compliant operating system, such as FreeBSD.
  <text>
    <noop>Reference: </noop>
    <link>http://en.wikipedia.org/wiki/RTorrent</link>
  </text>
</content>
