<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>BMon</textheader> 
  <namedlink href="%%documentsurl%%images/bmon.png">
    <rimg href="%%documentsurl%%images/bmon.jpg" />
  </namedlink>
  <text>bmon is a portable bandwidth monitor with multiple input methods and output modes. A set of architecture specific input modules provide the core with the listof interfaces and their counters. The core stores this counters and provides rate estimation including a history over the last 60 seconds, minutes, hours and days to the output modules which output them according to the configuration.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://freecode.com/projects/bmon/</link>
  </text>
</content>
