<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Ettercap</textheader> 
  <namedlink href="%%documentsurl%%images/ettercap.gif">
    <rimg href="%%documentsurl%%images/ettercap.jpg" />
  </namedlink>
  <text>Ettercap is a network sniffer/logger for ethernet LANs. It supports active and passive dissection of many protocols. Many sniffing modes were implemented to give you a powerful and complete sniffing suite.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://ettercap.sourceforge.net</link>
  </text>
</content>

