<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>IPTraf</textheader> 
  <namedlink href="%%documentsurl%%images/iptraf.gif">
    <rimg href="%%documentsurl%%images/iptraf.jpg" />
  </namedlink>
  <text>IP-Traf is an easy to use traffic monitoring tool which enables you to watch in- and outgoing traffic through several different devices.  If you want to keep track of your newtwork, then this program is made for you.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://freecode.com/projects/iptraf</link>
  </text>
</content>
