<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>lftp - Sophisticated file transfer program</textheader> 
  <namedlink href="%%documentsurl%%images/lftp.png">
    <rimg href="%%documentsurl%%images/lftp_s.png" />
  </namedlink>
  <text>lftp is a file transfer program that allows sophisticated ftp, http and other connections to other hosts. If site is specified then lftp will connect to that site otherwise a connection has to be established with the open command.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://lftp.yar.ru</link>
  </text>
</content>
