<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>yafc - Yet another FTP client</textheader> 
  <namedlink href="%%documentsurl%%images/yafc.png">
    <rimg href="%%documentsurl%%images/yafc_s.png" />
  </namedlink>
  <text>Yafc is quite a powerful ftp client. It is a console interface to the ftp protocol. If you are looking for a nice GUI client, Yafc is not for you. If you, however, use ftp often and want a fast, powerful, friendly client Yafc is here for you... Yafc also speaks lots of other protocols.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://yafc.sourceforge.net/</link>
  </text>
</content>
