<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>MP3 Blaster</textheader> 
  <namedlink href="%%documentsurl%%images/mp3blaster.gif">
    <rimg href="%%documentsurl%%images/mp3blaster.jpg" />
  </namedlink>
  <text>The mp3blaster is an excelent tool for listenig mp3-soundfiles through the console. It combines an easy to use ASCII user interface and supports many features such as play-groups and group management, toggle-mode et cetera.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://mp3blaster.sourceforge.net/</link>
  </text>
</content>

