<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>MPlayer</textheader> 
  <namedlink href="%%documentsurl%%images/mplayer.gif">
    <rimg href="%%documentsurl%%images/mplayer.jpg" />
  </namedlink>
 <text>MPlayer is a movie player for LINUX (runs on many other Unices and non-x86 CPUs, see the documentation). It plays most MPEG/VOB, AVI, ASF/WMA/WMV, RM, QT/MOV/MP4, OGG/OGM, VIVO, FLI, NuppelVideo, yuv4mpeg, FILM and RoQ files, supported by many native, XAnim, and Win32 DLL codecs. You can watch VideoCD, SVCD, DVD, 3ivx, DivX 3/4/5 and even WMV movies, too (without using the avifile library).</text>
 <text> At the screenshot mplayer runs via AAlib in an ASCII FreeBSD console but also runs per SVGAlib in order to see colors and graphics in the videos.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.mplayerhq.hu</link>
  </text>
</content>
