<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>elvis - a clone of the ex/vi text editor</textheader>
  <namedlink href="%%documentsurl%%images/elvis.png">
    <rimg href="%%documentsurl%%images/elvis_s.png" />
  </namedlink>
  <text>Elvis  is a text editor. It is intended to be a modern replacement for the classic ex/vi editor of UNIX fame. Elvis supports many new features, including multiple edit buffers, multiple windows, multiple user interfaces (including an X11  interface), and a variety of display modes.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://elvis.vi-editor.org</link>
  </text>
</content>

