<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>GNU Emacs</textheader> 
  <namedlink href="%%documentsurl%%images/emacs.gif">
    <rimg href="%%documentsurl%%images/emacs.jpg" />
  </namedlink>
  <text>Emacs is, like vi, very popular too by unix/linux users. But Emacs is much bigger and has more features than vi has (Emacs brings it beyond the 90 MB mark with the sources + the binaries together). If you do not like vi, then you might would like to take a look on Emacs.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.gnu.org/software/emacs</link>
  </text>
</content>
