<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>GNU Nano - Nano's ANOther editor, an enhanced free Pico Clone</textheader>
  <namedlink href="%%documentsurl%%images/nano.gif">
    <rimg href="%%documentsurl%%images/nano.jpg" />
  </namedlink>
  <text>Nano is a small, free and friendly editor which aims to replace Pico, the default editor included in the  non-free Pine  package.  Rather  than  just copying Pico's look and feel, nano also implements some missing  (or  disabled  by default)  features  in  Pico, such as "search and replace" and "goto line number".</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.nano-editor.org</link>
  </text>
</content>

