<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Joe - Joe's Own Editor</textheader> 
  <namedlink href="%%documentsurl%%images/joe.gif">
    <rimg href="%%documentsurl%%images/joe.jpg" />
  </namedlink>
  <text>JOE is a powerful ASCII-text screen editor. It has a "mode-less" user interface which is similer to many user-friendly PC editors.  Users  of Micro-Pro's  WordStar or Borland's "Turbo" languages will feel at home.  JOE is a full featured UNIX screen-editor though, and has many features for editing programs and text.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://sourceforge.net/projects/joe-editor</link>
  </text>
</content>
