<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>pico - simple text editor in the style of the Alpine Composer</textheader>
  <namedlink href="%%documentsurl%%images/pico.png">
    <rimg href="%%documentsurl%%images/pico_s.png" />
  </namedlink>
  <text>Pico is a simple, display-oriented text editor based on the Alpine message system composer. As with Alpine, commands are displayed at the bottom of the screen, and context-sensitive help is provided. As characters are typed they are immediately inserted into the text.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.washington.edu/alpine</link>
  </text>
</content>

