<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>VIM - Vi IMproved</textheader> 
  <namedlink href="%%documentsurl%%images/vim.gif">
    <rimg href="%%documentsurl%%images/vim.jpg" />
  </namedlink>
  <text>This is my favoite text-editor. With vim i programmed this whole homepage.  Standardly, vim supports syntax-highlighting for over 300 file-formats and programming languages and on every linux-destribution you will find a copy of it.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.vim.org</link>
  </text>
</content>
