<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>BitchX</textheader> 
  <namedlink href="%%documentsurl%%images/bitchx.gif">
    <rimg href="%%documentsurl%%images/bitchx.jpg" />
  </namedlink>
  <text>BitchX is a VERY heavily modified ircII client. It includes many things such as built in CDCC (XDCC) offering, built in flood protection, etc.  It is easier to script things in BitchX because unlike plain, vanilla ircII, half the script does not have to be devoted to changing the appearance of ircII. It also includes many other new features, such as port scanning, advanced TCL, a CD player, a mail client, screening process, etc.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.bitchx.org</link>
  </text>
</content>
