<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>EPIC - Internet Relay Chat client for UNIX like systems</textheader>
  <namedlink href="%%documentsurl%%images/epic.png">
    <rimg href="%%documentsurl%%images/epic.jpg" />
  </namedlink>
  <text>The ircII/EPIC program is a unix-based character oriented user agent ('client') to Internet Relay Chat. It is a fully functional ircII client with many useful extensions. This version works with all modern irc server classes as of early 1999.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://prbh.org</link>
  </text>
</content>
