<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>ircII - interface to the Internet Relay Chat system</textheader>
  <namedlink href="%%documentsurl%%images/ircII.png">
    <rimg href="%%documentsurl%%images/ircII_s.png" />
  </namedlink>
  <text>The ircII program is a full screen, termcap based interface to Internet Relay Chat. It gives full access to all of the normal IRC functions, plus a variety of additional options. It is one of the very first IRC client programs.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.eterna.com.au/ircii/</link>
  </text>
</content>
