<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>IRSSI</textheader> 
  <namedlink href="%%documentsurl%%images/irssi.png">
    <rimg href="%%documentsurl%%images/irssi.jpg" />
  </namedlink>
  <text>Irssi is a modular IRC client for UNIX that currently has only text mode user interface, but 80-90% of the code isn't text mode specific, so other UIs could be created pretty easily. Also, Irssi isn't really even IRC specific anymore, there's already working SILC and ICB modules available. Support for other protocols like ICQ and Jabber could be created some day too.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.irssi.org</link>
  </text>
</content>
