<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/hyperion.jpg">
		<rimg href="%%documentsurl%%images/hyperion-small.jpg" />
	</namedlink>
	<textheader>Hyperion / Der Sturz von Hyperion</textheader>
	<text>Im Vordergrund stehen die sieben Protagonisten, die zu einer letzten Pilgerfahrt nach Hyperion aufbrechen, um dort eines der letzten ungel&ouml;sten Geheimnisse des Universums zu l&uuml;ften: die Zeitgr&auml;ber, die sich scheinbar aus der Zukunft kommend r&uuml;ckw&auml;rts in der Zeit bewegen. Umgeben von einem "Anti-Entropiefeld", das zuweilen starke St&ouml;rungen in der Zeitlinie hervorrufen kann, dient es zugleich als Gef&auml;ngnis f&uuml;r das Shrike. Dieses legend&auml;re Dornenwesen -- gef&uuml;rchtet von den meisten, angebetet von seinen J&uuml;ngern -- besitzt Kontrolle &uuml;ber die Zeit und kann so in Sekundenschnelle Armeen abmetzeln. Und eben diese Felder, die als einzige ein planetenweites Massaker verhindern, beginnen sich seit einiger Zeit aufzul&ouml;sen und drohen bald vollkommen zu verfallen.</text>
	<text>Die Wichtigkeit der Pilgerfahrt ergibt sich auch aus einer weiteren Tatsache. Vor langer Zeit, als die Erde durch den "Gro&szlig;en Fehler" zerst&ouml;rt wurde, hatten sich die Menschen auf viele entlegene Planeten, die nur aufgrund der sie verbindenden "Farcaster" ein Netz bilden, zerstreut. Nur ein kleiner Teil, die sogenannten "Ousters", hatten sich vom Rest losgesagt und die Reise in unbekannte Teile der Galaxie angetreten. Diese "Ousters" planen nun eine Offensive gegen das "Netz", und der Planet, den sie zuerst in ihre Gewalt bringen wollen, ist Hyperion. Falls sie das Geheimnis der Zeitgr&auml;ber l&ouml;sen k&ouml;nnen, kann sich ihnen nichts mehr in den Weg stellen.</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction</text>
		</enumitem>
		<enumitem>
			<text>Autor: Dan Simmons</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 1456</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: 5/5</text>
		</enumitem>
	</enumeration>
</content>
