<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/der_zeitkrieg.jpg">
		<rimg href="%%documentsurl%%images/der_zeitkrieg-small.jpg" />
	</namedlink>
	<textheader>Der Zeitkrieg</textheader>
	<text>Erfolgreiche Science Fiction aus Deutschland, die den Vergleich mit den gro&szlig;en amerikanischen Vorbildern nicht zu scheuen braucht! Nach Diamant und Der Metamorph der neue Roman von Andreas Brandhorst, der uns in die mysteri&ouml;seWelt der Kantaki entf&uuml;hrt, einer au&szlig;erirdischen Zivilisation, die den letzten R&auml;tseln des Universums auf der Spur ist.</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Space Opera, Fantasy, Zeitreise</text>
		</enumitem>
		<enumitem>
			<text>Autor: Andreas Brandhorst</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 592</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: 4/5</text>
		</enumitem>
	</enumeration>
</content>
