<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/feuersvoegel.jpg">
		<rimg href="%%documentsurl%%images/feuervoegel-small.jpg" />
	</namedlink>
	<textheader>Feuerv&ouml;gel</textheader>
	<text>Ein Weltraumabenteuer im Stile von Andreas Eschbachs "Quest" Mit "Feuerv&ouml;gel" entf&uuml;hrt uns Andreas Brandhorst ein weiteres Mal in die mysteri&ouml;se Welt der Kantaki, einer au&szlig;erirdischen Zivilisation, die den letzten R&auml;tseln des Universums auf der Spur ist.</text> 
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Space Opera, Fantasy</text>
		</enumitem>
		<enumitem>
			<text>Autor: Andreas Brandhorst</text>
		</enumitem>
		<enumitem>
			<text>Seiten: 580</text>
		</enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: 5/5</text>
		</enumitem>
	</enumeration>
</content>
