<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/der_metamorph.jpg">
		<rimg href="%%documentsurl%%images/der_metamorph-small.jpg" />
	</namedlink>
	<textheader>Der Metamorph</textheader>
	<text>Aufgrund seiner isolierten Lage - am Rande des von Menschen besiedelten Teils der Galaxis - ist der Planet Kerberos bestens geeignet f&uuml;r ein geheimes Projekt zur Schaffung neuer, h&ouml;chst anpassungsf&auml;higer Lebensformen. Als jedoch auf eines der Labors ein Anschlag ver&uuml;bt wird, ger&auml;te der unscheinbare Planet ins Visier der untereinander verfeindeten Machtbl&ouml;cke. Denn auf Kerberos erwacht ein Wesen zum Leben, das alle Zivilisationen im Universum zu vernichten droht ...</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Space Opera, Fantasy, Zeitreise</text>
		</enumitem>
		<enumitem>
			<text>Autor: Andreas Brandhorst</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 608</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: 4/5</text>
		</enumitem>
	</enumeration>
</content>
