<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/collector.jpg">
		<rimg href="%%documentsurl%%images/collector-small.jpg" />
	</namedlink>
	<textheader>Collector</textheader>
	<text>Wir schreiben das Jahr 3042. Die Menschheit ist ins Weltall aufgebrochen, doch nicht mit eigener Technik, sondern mit Hilfe von Objekten, die man bei Ausgrabungen auf der Erde gefunden hat: au&szlog;erirdische Hinterlassenschaften, die zwar funktionieren, deren Funktionsweise die menschlichen Piloten jedoch nur in Ans&auml;tzen verstehen. So verl&auml;uft die Besiedelung anderer Planeten denkbar chaotisch. Doch dann treffen die Menschen auf eine au&szlig;erirdische Spezies - die Collectors - die anbietet, die menschliche Zivilisation unter ihre Fittiche zu nehmen und in die Gemeinschaft der galaktischen V&ouml;lker einzuf&uuml;hren. Ein Angebot, das die Menschen nicht ablehnen k&ouml;nnen - mit katastrophalen Folgen ...</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Space Opera</text>
		</enumitem>
		<enumitem>
			<text>Autor: Markus Heitz</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 656</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: 3/5</text>
		</enumitem>
	</enumeration>
</content>
