<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <namedlink href="%%documentsurl%%images/unendlichkeit.jpg">
	<rimg href="%%documentsurl%%images/unendlichkeit-small.jpg" />
  </namedlink>
	<textheader>Unendlichkeit</textheader>
  <text>Auf einem Bergarbeiterplaneten mit lebensfeindlicher Umwelt werden bei arch&auml;ologischen Forschungen Artefakte einer untergegangenen Kultur entdeckt. Schon bald zeigt sich, dass die Erschaffer der Artefakte damit eine Katastrophe heraufbeschworen hatten, die sie selbst vernichtet hat. Und die Entdeckung birgt ungeahnte Gefahren f&uuml;r die gesamte Menschheit, denn die Relikte der verschwundenen Zivilisation f&uuml;hren an die Grenzen von Raum und Zeit - und dar&uuml;ber hinaus.</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Fantasy</text>
		</enumitem>
		<enumitem>
			<text>Autor: Alastair Reynolds; &Uuml;bersetzer: Irene Holicki</text>
		</enumitem>
		<enumitem>
			<text>Seiten: 768</text>
		</enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: 5/5</text>
		</enumitem>
  </enumeration>
</content>
