<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <namedlink href="%%documentsurl%%images/jagt_auf_ikarus.jpg">
	<rimg href="%%documentsurl%%images/jagt_auf_ikarus-small.jpg" />
  </namedlink>
	<textheader>Jagt auf Ikarus</textheader>
  <text>Als Jordan McKell, seines Zeichens Schmuggler und Kapit&auml;n ohne Raumschiff, den Auftrag erh&auml;lt, die Ikarus samt hochbrisanter Ware zur Erde zu fliegen, sieht er zun&auml;chst keine gr&ouml;&szlig;eren Probleme auf sich zukommen. Doch ehe er sichs versieht, ist er in eine intergalaktische Handelsverschw&ouml;rung verwickelt, und das halbe Universum ist ihm auf den Fersen...
	</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Spare Opera</text>
		</enumitem>
		<enumitem>
			<text>Autor: Timothy Zahn; &Uuml;bersetzer: Martin Gilbert</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 608</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: 4,5/5</text>
		</enumitem>
  </enumeration>
</content>
