<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/das_artefakt.png">
		<rimg href="%%documentsurl%%images/das_artefakt-small.png" />
	</namedlink>
	<textheader>Das Artefakt</textheader>
	<text>Dies ist die letzte Chance der Menschheit: Nachdem sie eine interstellare Katastrophe verursacht haben, die nur durch das Eingreifen der Hohen M&auml;chte einged&auml;mmt werden konnte, m&uuml;ssen die Menschen innerhalb von 600 Jahren beweisen, dass sie zu dauerhaftem Frieden f&auml;hig sind. Und das Vorhaben der Menschen scheint unter einem guten Stern zu stehen: Der Planet Heraklon wird zum Zentrum des Friedens und der Diplomatie. Doch dann taucht ein uraltes Artefakt auf, so m&auml;chtig, dass es den Technologien der Hohen M&auml;chte ebenb&uuml;rtig ist - und der Krieg beginnt aufs Neue ...</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Space Opera </text>
		</enumitem>
		<enumitem>
			<text>Autor: Andreas Brandhorst</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 608</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: ?/5</text>
		</enumitem>
	</enumeration>
</content>
