<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/quest.png">
		<rimg href="%%documentsurl%%images/quest-small.png" />
	</namedlink>
	<textheader>Quest</textheader>
	<text>Das Reich Gheera steht vor dem Untergang. Die Verteidigungskr&auml;fte haben keine Chance gegen die &uuml;berm&auml;chtigen Legionen des sagenhaften Sternenkaisers, dessen Machtgier keine Grenzen kennt. Der endg&uuml;ltige Fall ist nur noch eine Frage der Zeit. In dieser Situation begibt sich der Kommandant Eftalan Quest, ein ehrgeiziger Mann, der sein Schiff mit harter Hand f&uuml;hrt, auf eine schier aussichtslose Expedition: Er will den sagenhaften Planeten des Ursprungs finden - die Welt, von der angeblich alles Leben im Universum stammt. Doch es gibt noch andere Legenden um diese Welt ..</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Space Opera </text>
		</enumitem>
		<enumitem>
			<text>Autor: Andreas Eschbach</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 506</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: ?/5</text>
		</enumitem>
	</enumeration>
</content>
