<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <namedlink href="%%documentsurl%%images/chasm_city.jpg">
	<rimg href="%%documentsurl%%images/chasm_city-small.jpg" />
  </namedlink>
	<textheader>Chasm City</textheader>
  <text>Mit seinem zweiten Roman kehrt Alastair Reynolds in die Welt seiner erfolgreiche Space Opera Unendlichkeit zur&uuml;ck. Er erz&auml;hlt die zun&auml;chst simpel erscheinende Geschichte von Tanner Mirabel, der zuletzt f&uuml;r den Waffenschmuggler Calhuella als Leibw&auml;chter gearbeitet hat. Jetzt macht der ehemalige Elitesoldat Jagd auf den reichen Aristokraten Argent Reivich, den er f&uuml;r den Tod seines Chefs und dessen von Mirabel geliebten Ehefrau verantwortlich macht. Die Jagd f&uuml;hrt ihn vom Planeten Sky's Edge nach Chasm City, der Hauptstadt des Planeten Yellowstone.</text>
<text>Chasm City ist bereits vor Jahren der geheimnisvollen "Schmelzseuche" zum Opfer gefallen: Sowohl die Infrastruktur der Stadt als auch deren Bewohner selbst waren von Nanomaschinen abh&auml;ngig, und nachdem diese durch die Seuche zerst&ouml;rt worden sind, ist nichts mehr, wie es sein sollte. Auch Mirabel nimmt eigenartige Ver&auml;nderungen an sich wahr: In ihm manifestiert sich zunehmend die Pers&ouml;nlichkeit des ber&uuml;hmt-ber&uuml;chtigten Sky Haussmann, einem der Gr&uuml;nderv&auml;ter seines Heimatplaneten.</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Fantasy</text>
		</enumitem>
		<enumitem>
			<text>Autor: Alastair Reynolds; &Uuml;bersetzer: Irene Holicki</text>
		</enumitem>
		<enumitem>
			<text>Seiten: 832</text>
		</enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: ?/5</text>
		</enumitem>
  </enumeration>
</content>
