<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/weltensturm.jpg">
		<rimg href="%%documentsurl%%images/weltensturm-small.jpg" />
	</namedlink>
	<textheader>Weltensturm</textheader>
	<text>Das Reich der Achtzig Welten wird seit 1600 Jahren von einem Kaiser regiert, der den Tod &uuml;berwunden hat und nahezu unsterblich ist. Einst ein gro&szlig;er Wissenschaftler hat der Kaiser eine M&ouml;glichkeit gefunden, Tote wieder zum Leben zu erwecken, und mit diesem Wissen erh&auml;lt er eine Dynastie aufrecht, die einen Gro&szlig;teil der von Menschen besiedelten Galaxis umfasst. Doch die Macht des Kaisers ist nicht unangefochten - die Rix, ein fanatischer Kult von Frauen, die ihre K&ouml;rper mit Hilfe von Cyborg-Implantaten umgestaltet haben, will das Reich mit K&uuml;nstlichen Intelligenzen besiedeln, die sie wie G&ouml;tter anbeten.</text>
	<enumeration>
		<enumitem>
			<text>Genre: Sience Fiction, Space Opera, Fantasy</text>
		</enumitem>
		<enumitem>
			<text>Autor: Scott Westerfeld; &Uuml;bersetzer: Andreas Brandhorst</text>
		</enumitem>
                <enumitem>
                        <text>Seiten: 832</text>
                </enumitem>
		<enumitem>
			<text>Pers&ouml;nliche Wertung: ?/5</text>
		</enumitem>
	</enumeration>
</content>
