<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Links</textheader> 
  <namedlink href="%%documentsurl%%images/links.png">
    <rimg href="%%documentsurl%%images/links.jpg" />
  </namedlink>
 <text>Links is a text mode WWW browser with ncurses interface, supporting colors, correct table rendering, background downloading, menu driven configuration interface and slim code. Frames are supported. You can have different file formats associated with external viewers. mailto: and telnet: are supported via external clients. If you have installed svgalib you may use links in graphical console mode.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://atrey.karlin.mff.cuni.cz/~clock/twibright/links/</link>
  </text>
</content>

