<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Lynx</textheader> 
  <namedlink href="%%documentsurl%%images/lynx.gif">
    <rimg href="%%documentsurl%%images/lynx.jpg" />
  </namedlink>
  <text>Lynx is the most porpular text-only webbrowser out there. Although Lynx cannot display any web-graphics, framesets and tables, this tool is very comfortable to surf the internet if you know sites with less graphics and special features. This site is also browsable with Lynx.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://freecode.com/projects/lynx</link>
  </text>
</content>
