<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>W3M - Webbrowser / pager</textheader> 
  <namedlink href="%%documentsurl%%images/w3m.png">
    <rimg href="%%documentsurl%%images/w3m.jpg" />
  </namedlink>
 <text>w3m is a World Wide Web (WWW) text based client. It has English and Japanese help files and an option menu and can be configured to use either language. It will display hypertext markup language (HTML) documents containing links to files residing on the local system, as well as files residing on remote systems. It can display HTML tables and frames. In addition, it can be used as a "pager" in much the same manner as "more" or "less". </text> 
  <text>
    <noop>Homepage: </noop>
    <link>http://www.w3m.org</link>
  </text>
</content>
