<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/neogeo-metalslugx.jpg">
		<rimg href="%%documentsurl%%images/neogeo-metalslugx-small.jpg" />
	</namedlink>
	<textheader>Metal Slug X</textheader>
	<enumeration>
		<enumitem>
			<text>Platform: Neo Geo</text>
		</enumitem>
		<enumitem>
			<text>Publisher: SNK</text>
		</enumitem>
		<enumitem>
			<text>Release year: 1999</text>
		</enumitem>
		<enumitem>
			<text>Size: 512 Megs</text>
		</enumitem>
		<enumitem>
			<text>Note: Revised Metal Slug 2</text>
		</enumitem>
	</enumeration>
</content>
