<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/neogeo-metalslug4.jpg">
		<rimg href="%%documentsurl%%images/neogeo-metalslug4-small.jpg" />
	</namedlink>
	<textheader>Metal Slug 4</textheader>
	<enumeration>
		<enumitem>
			<text>Platform: Neo Geo</text>
		</enumitem>
		<enumitem>
			<text>Publisher: SNK</text>
		</enumitem>
		<enumitem>
			<text>Release year: 2002</text>
		</enumitem>
		<enumitem>
			<text>Size: 560 Megs</text>
		</enumitem>
	</enumeration>
</content>
