<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/neogeo-metalslug2.jpg">
		<rimg href="%%documentsurl%%images/neogeo-metalslug2-small.jpg" />
	</namedlink>
	<textheader>Metal Slug 2</textheader>
	<enumeration>
		<enumitem>
			<text>Platform: Neo Geo</text>
		</enumitem>
		<enumitem>
			<text>Publisher: SNK</text>
		</enumitem>
		<enumitem>
			<text>Release year: 1998</text>
		</enumitem>
		<enumitem>
			<text>Size: 352 Megs</text>
		</enumitem>
	</enumeration>
</content>
