<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/neogeo-metalslug6.jpg">
		<rimg href="%%documentsurl%%images/neogeo-metalslug6-small.jpg" />
	</namedlink>
	<textheader>Metal Slug 6 (Bootleg)</textheader>
	<enumeration>
		<enumitem>
			<text>Platform: Neo Geo</text>
		</enumitem>
		<enumitem>
			<text>Publisher: SNK</text>
		</enumitem>
		<enumitem>
			<text>Release year: ????</text>
		</enumitem>
		<enumitem>
			<text>Size: ??? Megs</text>
		</enumitem>
		<enumitem>
			<text>Note: Custom Metal Slug Remix</text>
		</enumitem>
	</enumeration>
</content>
