<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/neogeo-metalslug5.jpg">
		<rimg href="%%documentsurl%%images/neogeo-metalslug5-small.jpg" />
	</namedlink>
	<textheader>Metal Slug 5</textheader>
	<enumeration>
		<enumitem>
			<text>Platform: Neo Geo</text>
		</enumitem>
		<enumitem>
			<text>Publisher: SNK</text>
		</enumitem>
		<enumitem>
			<text>Release year: 2003</text>
		</enumitem>
		<enumitem>
			<text>Size: 712 Megs</text>
		</enumitem>
	</enumeration>
</content>
