<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
	<namedlink href="%%documentsurl%%images/neogeo-cyberlip.jpg">
		<rimg href="%%documentsurl%%images/neogeo-cyberlip-small.jpg" />
	</namedlink>
	<textheader>Cyberlip</textheader>
	<enumeration>
		<enumitem>
			<text>Platform: Neo Geo</text>
		</enumitem>
		<enumitem>
			<text>Publisher: SNK</text>
		</enumitem>
		<enumitem>
			<text>Release year: 1990</text>
		</enumitem>
		<enumitem>
			<text>Size: 75 Megs</text>
		</enumitem>
	</enumeration>
</content>
