<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Aptitude</textheader> 
  <namedlink href="%%documentsurl%%images/aptitude.png">
    <rimg href="%%documentsurl%%images/aptitude.jpg" />
  </namedlink>
  <text>aptitude is a terminal-based apt frontend with a number of useful features, including: a mutt-like syntax for matching packages in a flexible manner, dselect-like persistence of user actions, the ability to retrieve and display the Debian changelog of most packages, and a command-line mode similar to that of apt-get.</text>
  <text>
    <noop>Reference: </noop>
    <link>http://packages.debian.org/de/etch/aptitude</link>
  </text>
</content>
