<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>CFDisk</textheader> 
  <namedlink href="%%documentsurl%%images/cfdisk.gif">
    <rimg href="%%documentsurl%%images/cfdisk.jpg" />
  </namedlink>
  <text>Cfdisk is a comfortable hard-disk partition management tool. Its use is mich easier as the standard fdisk-programm. You cann create and delete partitions and you are also able to change their file-system types etc.</text>
  <text>Operating system: Linux</text>
</content>
