<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>HTop</textheader> 
  <namedlink href="%%documentsurl%%images/htop.png">
    <rimg href="%%documentsurl%%images/htop.jpg" />
  </namedlink>
  <text>This program is a free (GPL) ncurses-based process viewer. It is similar to top, but allows to scroll the list vertically and horizontally to see all processes and their full command lines. Tasks related to processes (killing,  renicing)  can  be  done  without entering their PIDs. It is much more comfortable than top</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://htop.sourceforge.net/</link>
  </text>
</content>
