<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Top</textheader> 
  <namedlink href="%%documentsurl%%images/top.gif">
    <rimg href="%%documentsurl%%images/top.jpg" />
  </namedlink>
  <text>Top shows you all currently running processes on your machine and sorts them by their percentages of CPU usages. If you want to keep track of certain groups of processes you will be able to specify some filter features such as "show all processes of a certain user" etc.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.groupsys.com/top</link>
  </text>
</content>
