<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Mutt - The Mutt Mail User Agent</textheader>
  <namedlink href="%%documentsurl%%images/mutt.png">
    <rimg href="%%documentsurl%%images/mutt.jpg" />
  </namedlink>
  <text>Mutt is a insidetable but very powerful text based program for reading  electronic  mail under unix operating systems, including support color terminals, MIME, and a threaded sorting mode.  Mutt is able to read mails from imap, pop3 servers and as well as from the local spool directory. Very neat program which i use too.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.mutt.org</link>
  </text>
</content>
