<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>slrn - An easy to use NNTP / spool based newsreader</textheader>
  <namedlink href="%%documentsurl%%images/slrn.png">
    <rimg href="%%documentsurl%%images/slrn.jpg" />
  </namedlink>
  <text>slrn is an easy to use but powerful NNTP / spool based newsreader.</text>
  <text>It  is highly customizable, supports scoring, free key bindings and can be extended using the s-lang macro language.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.slrn.org</link>
  </text>
</content>

