<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Snownews - Console RSS newsreader</textheader> 
  <namedlink href="%%documentsurl%%images/snownews.png">
    <rimg href="%%documentsurl%%images/snownews.jpg" />
  </namedlink>
  <text>Snownews  is a small console RSS/RDF newsreader. It will handle RSS 1.0 feeds that comply with the W3C RDF specification, but will also support userland's 0.91 and 2.0 versions.</text>
  <text>The main program screen that is shown left after you start the application lets you add/remove feeds and update them manually. On the left side of the screen the number of new items is shown for every newsfeed.  To add a feed press 'a' and enter the URL. This must be a  fully  valid http  URL  including  http:// at the beginning. To delete a listed feed highlight it with the cursor keys and press 'D'.  A dialog will ask for confirmation.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://home.kcore.de/~kiza/software/snownews/</link>
  </text>
</content>
