<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>
<content>
  <textheader>Tin - A threaded NNTP and spool based UseNet newsreader</textheader>
  <namedlink href="%%documentsurl%%images/tin.gif">
    <rimg href="%%documentsurl%%images/tin.jpg" />
  </namedlink>
  <text>Tin is a full-screen easy to use Usenet newsreader. It can read news  locally  (i.e.,  /var/spool/news)  or  remotely (rtin or tin -r option) via a NNTP (Network News Transport Protocol)  server.  It  will  automatically  utilize   NOV newsoverview(5)  style index files if available locally or via the NNTP [X]OVER command.</text>
  <text>tin has four separate levels of operation: Group selection level,  Group  level,  Thread level and Article level. Use the 'h' (help) command to view  a  list  of  the  commands available at a particular level.</text>
  <text>
    <noop>Homepage: </noop>
    <link>http://www.tin.org</link>
  </text>
</content>
  	

